FPCS.Web.Admin/Controllers/FamilyController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using System.Collections.Generic;

using FPCS.Data;
using FPCS.Data.Repo;
using FPCS.Data.Enums;
using FPCS.Web.Admin.Code;
using FPCS.Web.Admin.Models.Family;
using FPCS.Core.jqGrid;
using FPCS.Data.Entities;
using System.Configuration;
using System.Web.Script.Serialization;
using FPCS.Web.Admin.Models.GoodAndServiceApproval;
using ListPrintReimbursementModel = FPCS.Web.Admin.Models.Family.ListPrintReimbursementModel;
using PrintReimbursementModel = FPCS.Web.Admin.Models.Family.PrintReimbursementModel;
using ReimbursementModel = FPCS.Web.Admin.Models.Family.ReimbursementModel;

namespace FPCS.Web.Admin.Controllers
{
    public class FamilyController : BaseController
    {
        [FPCSAuthorize(Role.Admin, Role.Teacher)]
        public ActionResult Index()
        {
            FamilyIndexModel model = new FamilyIndexModel();
            model.Init(SchoolYear.SchoolYearId);

            return View(model);
        }

        [FPCSAuthorize(Role.Admin, Role.Teacher)]
        public JsonResult _Index(GridOptions options, FamilyListOptions familyListOptions, Int64? familyId)
        {
            using (var uow = UnityManager.Resolve<IUnitOfWork>())
            {
                var repo = uow.GetRepo<IFamilyRepo>();
                IQueryable<Family> dbList;

                if (familyId.HasValue && familyId.Value != 0)
                {
                    dbList = repo.GetAsQuery(familyId.Value);
                }
                else
                {
                    dbList = repo.GetAll(SchoolYear.SchoolYearId);
                }

                var engine = new GridDynamicEngine(options, familyListOptions);
                var result = engine.ApplyAll(dbList, x => new FamilyMiniModel
                {
                    FamilyId = x.FamilyId,
                    FamilyName = x.Name,
                    FirstNames = String.Empty,
                    Telephone = x.Telephone,
                    Email = x.Email,
                });

                var guardians = uow.GetRepo<IGuardianRepo>()
                                              .GetByFamilies(SchoolYear.SchoolYearId, result.rows.Select(t => t.FamilyId).ToList())
                                              .Select(x => new
                                              {
                                                  GuardianId = x.DbUserId,
                                                  GuardianFirstName = x.FirstName,
                                                  GuardianLastName = x.LastName,
                                                  FamilyIds = x.Families.Where(t => !t.IsDeleted).Select(t => t.FamilyId)
                                              })
                                              .ToList();

                foreach (var item in result.rows)
                {
                    var names = guardians.Where(x => x.FamilyIds.Contains(item.FamilyId)).Select(x => new { x.GuardianLastName, x.GuardianFirstName }).ToList();
                    var lastNames = names.Select(x => x.GuardianLastName).Distinct();

                    if (lastNames.Count() == 1)
                    {
                        item.FirstNames = names[0].GuardianLastName + ", " + String.Join(" & ", names.Select(x => x.GuardianFirstName));
                    }
                    else
                    {
                        item.FirstNames = String.Join(" - ", lastNames) + ", " + String.Join(" & ", names.Select(x => x.GuardianFirstName));
                    }
                }

                return Json(result);
            }
        }

        [FPCSAuthorize(Role.Admin, Role.Teacher)]
        [HttpGet]
        public ActionResult Create()
        {
            var model = new FamilyCreateModel();
            model.Init();
            model.FamilyGuardians = new List<LightGuardianModel>();
            model.FamilyStudents = new List<LightStudentModel>();
            return View(model);
        }

        [FPCSAuthorize(Role.Admin, Role.Teacher)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FamilyCreateModel model)
        {
            if (model.FamilyGuardians == null) model.FamilyGuardians = new List<LightGuardianModel>();
            if (model.FamilyStudents == null) model.FamilyStudents = new List<LightStudentModel>();

            if (ModelState.IsValid)
            {
                try
                {
                    using (var uow = UnityManager.Resolve<IUnitOfWork>())
                    {
                        String familyName = String.Empty;
                        if (model.FamilyGuardians.Count() != 0)
                        {
                            var repoDbUser = uow.GetRepo<IDbUserRepo>();
                            var guardianIds = model.FamilyGuardians.Select(t => t.DbUserId).ToList();
                            var guardians = repoDbUser.GetAll().Where(x => guardianIds.Contains(x.DbUserId)).ToList();

                            var names = guardians.Select(x => new { x.LastName, x.FirstName }).ToList();
                            var lastNames = names.Select(x => x.LastName).Distinct();

                            if (lastNames.Count() == 1) familyName = names[0].LastName;
                            else familyName = String.Join(" - ", lastNames);
                        }

                        var repo = uow.GetRepo<IFamilyRepo>();
                        var family = repo.Add(familyName, model.Description, model.Address, model.MailingAddress, model.Telephone, model.CellPhone, model.City,
                             model.Country, model.Zip, model.Email, model.Password, model.IsUseDirectory, model.StateId, SchoolYear.SchoolYearId);

                        uow.Commit();

                        family = repo.UpdateGuardians(family, model.FamilyGuardians.Select(x => x.DbUserId));
                        family = repo.UpdateStudents(family, model.FamilyStudents.Select(x => x.DbUserId));
                        uow.Commit();

                        return RedirectToAction("Index");
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            model.Init();
            return View("Create", model);
        }

        [FPCSAuthorize(Role.Admin, Role.Teacher)]
        [HttpGet]
        public ActionResult Edit(Int64 id)
        {
            using (var uow = UnityManager.Resolve<IUnitOfWork>())
            {
                var model = uow.GetRepo<IFamilyRepo>().GetAsQuery(id)
                    .Select(x => new FamilyEditModel
                    {
                        FamilyId = x.FamilyId,
                        Name = x.Name,
                        Description = x.Description,
                        Email = x.Email,
                        Password = x.Password,
                        Telephone = x.Telephone,
                        CellPhone = x.CellPhone,
                        Address = x.Address,
                        MailingAddress = x.MailingAddress,
                        City = x.City,
                        StateId = x.StateId,
                        Country = x.Country,
                        Zip = x.Zip,
                        IsUseDirectory = x.IsUseDirectory,
                        FamilyGuardians = x.Guardians
                            .Select(x2 => new LightGuardianModel { DbUserId = x2.DbUserId, FullName = x2.FullName, CellPhone = x2.CellPhone }),
                        FamilyStudents = x.Students
                            .Select(x3 => new LightStudentModel { DbUserId = x3.DbUserId, FullName = x3.FullName, GradYear = x3.GradYear, IsWithdrawal = x3.WithdrawalDate.HasValue ? true : false})
                    }).FirstOrDefault();

                if (model == null) return Error("Family {0} not found", id);

                model.Init();

                return View(model);
            }
        }

        [FPCSAuthorize(Role.Admin, Role.Teacher)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FamilyEditModel model)
        {
            if (model.FamilyGuardians == null) model.FamilyGuardians = new List<LightGuardianModel>();
            if (model.FamilyStudents == null) model.FamilyStudents = new List<LightStudentModel>();

            if (ModelState.IsValid)
            {
                try
                {
                    using (var uow = UnityManager.Resolve<IUnitOfWork>())
                    {
                        String familyName = String.Empty;
                        if (model.FamilyGuardians.Count() != 0)
                        {
                            var repoDbUser = uow.GetRepo<IDbUserRepo>();
                            var guardianIds = model.FamilyGuardians.Select(t => t.DbUserId).ToList();
                            var guardians = repoDbUser.GetAll().Where(x => guardianIds.Contains(x.DbUserId)).ToList();

                            var names = guardians.Select(x => new { x.LastName, x.FirstName }).ToList();
                            var lastNames = names.Select(x => x.LastName).Distinct();

                            if (lastNames.Count() == 1) familyName = names[0].LastName;
                            else familyName = String.Join(" - ", lastNames);
                        }

                        var repo = uow.GetRepo<IFamilyRepo>();
                        var family = repo.Update(model.FamilyId, familyName, model.Description, model.Address, model.MailingAddress, model.Telephone, model.CellPhone,
                            model.City, model.Country, model.Zip, model.Email, model.Password, model.IsUseDirectory, model.StateId);

                        uow.Commit();

                        family = repo.UpdateGuardians(family, model.FamilyGuardians.Select(x => x.DbUserId));

FPCS.Web.Admin/Controllers/GuardianController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using FPCS.Data;
using FPCS.Data.Repo;
using FPCS.Data.Enums;
using FPCS.Web.Admin.Code;
using FPCS.Web.Admin.Models.Guardian;
using FPCS.Core.jqGrid;
using System.Collections.Generic;
using FPCS.Data.Entities;

namespace FPCS.Web.Admin.Controllers
{
	public class GuardianController : BaseController
	{
		[FPCSAuthorize(Role.Admin, Role.Teacher, Role.Guardian)]
		public ActionResult Index()
		{
			return View();
		}

		[FPCSAuthorize(Role.Admin, Role.Teacher, Role.Guardian)]
		public JsonResult _Index(GridOptions options, GuardiansListOptions guardiansListOptions)
		{
			using (var uow = UnityManager.Resolve<IUnitOfWork>())
			{
				var repo = uow.GetRepo<IGuardianRepo>();
				var repoFamily = uow.GetRepo<IFamilyRepo>();
				IQueryable<Guardian> dbList;

				if (User.Role != Role.Guardian)
				{
					dbList = repo.GetAll(SchoolYear.SchoolYearId);
				}
				else
				{
					var familyIds = repoFamily.GetFamiliesByGuardian(User.UserId).Select(x => x.FamilyId).ToList();
					dbList = repo.GetByFamilies(SchoolYear.SchoolYearId, familyIds);
				} 

				var engine = new GridDynamicEngine(options, guardiansListOptions);
				var result = engine.ApplyAll(dbList, x => new GuardianMiniModel
				{
					DbUserId = x.DbUserId,
					FullName = x.LastName + ", " + x.FirstName,
					Email = x.Email,
					IsLocked = x.IsLocked ? "Locked" : "Active"
				});

				return Json(result);
			}
		}

		[FPCSAuthorize(Role.Admin, Role.Guardian, Role.Teacher)]
		[HttpGet]
		public ActionResult _Details(Guid id)
		{
			using (var uow = UnityManager.Resolve<IUnitOfWork>())
			{
				var repo = uow.GetRepo<IGuardianRepo>();
				var dbEntity = repo.Get(id);
				if (dbEntity == null) return JsonRes(Status.Error, "Guardian not found");

				var model = new GuardianDetailsModel
				{
					DbUserId = dbEntity.DbUserId,
					FirstName = dbEntity.FirstName,
					LastName = dbEntity.LastName,
					MiddleInitial = dbEntity.MiddleInitial,
					Employer = dbEntity.Employer,
					IsActiveMilitary = dbEntity.IsActiveMilitary,
					Rank = dbEntity.Rank,
					Pager = dbEntity.Pager,
					BusinessPhone = dbEntity.BusinessPhone,
					Ext = dbEntity.Ext,
					CellPhone = dbEntity.CellPhone,
					Email = dbEntity.Email,
					Address = dbEntity.Address,
					City = dbEntity.City,
					Country = dbEntity.Country,
					Zip = dbEntity.Zip,
					State = dbEntity.State == null ? "Same as for family" : dbEntity.State.Code
				};

				model.Init();
				return PartialView(model);
			}
		}

		[FPCSAuthorize(Role.Admin, Role.Teacher)]
		[HttpGet]
		public PartialViewResult _Create()
		{
			var model = new GuardianCreateModel();
			model.Init();
			
			return PartialView(model);
		}

		[FPCSAuthorize(Role.Admin, Role.Teacher)]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult _Create(GuardianCreateModel model)
		{
			if (ModelState.IsValid)
			{
				try
				{
					using (var uow = UnityManager.Resolve<IUnitOfWork>())
					{
						var repo = uow.GetRepo<IGuardianRepo>();
						var dbGuardian = repo.Add(model.FirstName, model.LastName, model.MiddleInitial, model.Employer,
							model.IsActiveMilitary, model.Rank, model.Pager, model.BusinessPhone, model.Ext, model.CellPhone,
							model.Email, model.Address, model.City, model.Country, model.Zip, model.StateId, SchoolYear.SchoolYearId);

						uow.Commit();

						dbGuardian.UnqDbUserId = dbGuardian.DbUserId;

						uow.Commit();

						//var sgRepo = uow.GetRepo<IFamilyRelationshipRepo>();
						//foreach (var item in model.GuardianRelationships)
						//{
						//	sgRepo.Update(dbGuardian.DbUserId, item.DbUserId, item.FamilyRelationshipType);
						//}

						//uow.Commit();

						return
							JsonRes(
								new
								{
									id = dbGuardian.DbUserId.ToString(),
									text = String.Format("{0}, {1}", dbGuardian.LastName, dbGuardian.FirstName)
								});
					}
				}
				catch (Exception ex)
				{
					ModelState.AddModelError("", ex.Message);
				}
			}

			model.Init();
			return PartialView(model);
		}

		[FPCSAuthorize(Role.Admin, Role.Guardian, Role.Teacher)]
		[HttpGet]
		public PartialViewResult _Edit(Guid id)
		{
			using (var uow = UnityManager.Resolve<IUnitOfWork>())
			{
				var dbEntity = uow.GetRepo<IGuardianRepo>().Get(id);
				if (dbEntity == null) return ErrorPartial("Guardian {0} not found", id);

				var model = new GuardianEditModel
				{
					DbUserId = dbEntity.DbUserId,
					FirstName = dbEntity.FirstName,
					LastName = dbEntity.LastName,
					MiddleInitial = dbEntity.MiddleInitial,
					Employer = dbEntity.Employer,
					IsActiveMilitary = dbEntity.IsActiveMilitary,
					Rank = dbEntity.Rank,
					Pager = dbEntity.Pager,
					BusinessPhone = dbEntity.BusinessPhone,
					Ext = dbEntity.Ext,
					CellPhone = dbEntity.CellPhone,
					Email = dbEntity.Email,
					Address = dbEntity.Address,
					City = dbEntity.City,
					Country = dbEntity.Country,
					Zip = dbEntity.Zip,
					StateId = dbEntity.StateId,
					GuardianRelationships = dbEntity.Relationships.Select(x =>
						new RelationshipModel
						{
							DbUserId = x.Student.DbUserId,
							FullName = x.Student.FullName,
							FamilyRelationshipType = x.FamilyRelationshipType
						}).ToList()
				};

				model.Init();
				return PartialView(model);
			}
		}

		[FPCSAuthorize(Role.Admin, Role.Guardian, Role.Teacher)]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult _Edit(GuardianEditModel model)
		{
			if (model.GuardianRelationships == null) model.GuardianRelationships = new List<RelationshipModel>();

			if (ModelState.IsValid)
			{
				try
				{
					using (var uow = UnityManager.Resolve<IUnitOfWork>())
					{
						var repo = uow.GetRepo<IGuardianRepo>();
						var dbEntity = repo.Update(model.DbUserId, model.FirstName, model.LastName, model.MiddleInitial, model.Employer,
							model.IsActiveMilitary, model.Rank, model.Pager, model.BusinessPhone, model.Ext, model.CellPhone,
							model.Email, model.Address, model.City, model.Country, model.Zip, model.StateId);

						var sgRepo = uow.GetRepo<IFamilyRelationshipRepo>();
						foreach (var item in model.GuardianRelationships)
						{
							sgRepo.Update(dbEntity.DbUserId, item.DbUserId, item.FamilyRelationshipType);
						}

						uow.Commit();
						return JsonRes(new {DbUserId = dbEntity.DbUserId, FullName = dbEntity.FullName, Phone = dbEntity.CellPhone});
					}
				}
				catch (Exception ex)
				{
					ModelState.AddModelError("", ex.Message);
				}
			}

			model.Init();
			return PartialView(model);
		}

		[FPCSAuthorize(Role.Admin, Role.Teacher)]
		[HttpPost]
		public ActionResult Delete(Guid id)
		{
			try
			{
				using (var uow = UnityManager.Resolve<IUnitOfWork>())
				{
					var repo = uow.GetRepo<IGuardianRepo>();
					repo.Remove(id);

					uow.Commit();
					return JsonRes();
				}
			}
			catch (Exception ex)
			{
				return JsonRes(Status.Error, ex.Message);
			}
		}

		[FPCSAuthorize(Role.Admin, Role.Teacher)]
		[HttpPost]
		public ActionResult DeleteAll(String id)
		{
			try
			{
				if (String.IsNullOrEmpty(id)) return JsonRes(Status.Error, "Not correct ids");

				var ids = id.Split(',');
				using (var uow = UnityManager.Resolve<IUnitOfWork>())
				{
					Int32 errorsCount = 0;
					var repo = uow.GetRepo<IGuardianRepo>();
					foreach (var item in ids)
					{
						try
						{
							repo.Remove(new Guid(item));
						}
						catch (Exception)
						{
							errorsCount++;
						}
					}

					uow.Commit();
					if (errorsCount == 0) return JsonRes();
					else return JsonRes(Status.Error, "Were deleted not all entities");
				}
			}
			catch (Exception ex)
			{
				return JsonRes(Status.Error, ex.Message);
			}
		}
	}
}

FPCS.Web.Admin/Views/Family/Edit.cshtml
@model FPCS.Web.Admin.Models.Family.FamilyEditModel
@using FPCS.Web.Admin.Models.Family;

@{
    ViewBag.Title = "Edit Family";
    ViewBag.Header = "Family Manager";
    ViewBag.SubHeader = "Edit Family";
}

@section head{
}

<div class="row-fluid">
    <div class="span8">

        @using (Html.BeginForm("Edit", "Family", FormMethod.Post, new { id = "editFamilyForm", @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
   
            <h3 class="header smaller lighter green">Main family information</h3>
    
            <div class="controls">
                @Html.ValidationSummary(true)
            </div>
    
            @Html.HiddenFor(x => x.FamilyId, new { id = "familyId" })

            @*<div class="control-group">
                @Html.LabelFor(x => x.Name, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextBoxFor(x => x.Name, new { placeholder = Html.DisplayNameFor(x => x.Name), @class = "span6"/*, @disabled = "true", @readonly = "true"*/ })
                    @Html.ValidationMessageFor(m => m.Name)
                </div>
            </div>
            <div class="control-group">
                @Html.LabelFor(x => x.Description, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextAreaFor(x => x.Description, new { placeholder = Html.DisplayNameFor(x => x.Description), @class = "autosize-transition span6" })
                    @Html.ValidationMessageFor(m => m.Description)
                </div>
            </div>*@
            <div class="control-group">
                @Html.LabelFor(x => x.Email, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextBoxFor(x => x.Email, new { placeholder = Html.DisplayNameFor(x => x.Email), @class = "span12" })
                    @Html.ValidationMessageFor(m => m.Email)
                </div>
            </div>
            <div class="control-group">
                @Html.LabelFor(x => x.Password, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextBoxFor(x => x.Password, new { placeholder = Html.DisplayNameFor(x => x.Password), @class = "span12" })
                    @Html.ValidationMessageFor(m => m.Password)
                </div>
            </div>
            @*<div class="row-fluid">
                <div class="span12">
                    <div class="span6 mleft0">
                        <div class="control-group">
                            @Html.LabelFor(x => x.Telephone, new { @class = "control-label" })
                            <div class="controls">
                                @Html.TextBoxFor(x => x.Telephone, new { placeholder = Html.DisplayNameFor(x => x.Telephone), @class = "span12" })
                                @Html.ValidationMessageFor(m => m.Telephone)
                            </div>
                        </div>
                    </div>
                    <div class="span6 mleft0">
                        <div class="control-group">
                            @Html.LabelFor(x => x.CellPhone, new { @class = "control-label" })
                            <div class="controls">
                                @Html.TextBoxFor(x => x.CellPhone, new { placeholder = Html.DisplayNameFor(x => x.CellPhone), @class = "span12" })
                                @Html.ValidationMessageFor(m => m.CellPhone)
                            </div>
                        </div>
                    </div>
                </div>
            </div>*@
            <div class="control-group">
                @Html.LabelFor(x => x.Telephone, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextBoxFor(x => x.Telephone, new { placeholder = Html.DisplayNameFor(x => x.Telephone), @class = "span12" })
                    @Html.ValidationMessageFor(m => m.Telephone)
                </div>
            </div>
            <div class="control-group">
                @Html.LabelFor(x => x.CellPhone, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextBoxFor(x => x.CellPhone, new { placeholder = Html.DisplayNameFor(x => x.CellPhone), @class = "span12" })
                    @Html.ValidationMessageFor(m => m.CellPhone)
                </div>
            </div>
            <div class="control-group">
                @Html.LabelFor(x => x.Address, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextBoxFor(x => x.Address, new { placeholder = Html.DisplayNameFor(x => x.Address), @class = "span12" })
                    @Html.ValidationMessageFor(m => m.Address)
                </div>
            </div>
            <div class="control-group">
                @Html.LabelFor(x => x.MailingAddress, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextBoxFor(x => x.MailingAddress, new { placeholder = Html.DisplayNameFor(x => x.MailingAddress), @class = "span12" })
                    @Html.ValidationMessageFor(m => m.MailingAddress)
                </div>
            </div>
            <div class="control-group">
                @Html.LabelFor(x => x.City, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextBoxFor(x => x.City, new { placeholder = Html.DisplayNameFor(x => x.City), @class = "span12" })
                    @Html.ValidationMessageFor(m => m.City)
                </div>
            </div>
            <div class="control-group">
                @Html.LabelFor(x => x.StateId, new { @class = "control-label" })
                <div class="controls">
                    @Html.DropDownListFor(x => x.StateId, Model.States, new { @class = "span12" })
                    @Html.ValidationMessageFor(m => m.StateId)
                </div>
            </div>
            @*<div class="control-group">
                @Html.LabelFor(x => x.Country, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextBoxFor(x => x.Country, new { placeholder = Html.DisplayNameFor(x => x.Country), @class = "span6" })
                    @Html.ValidationMessageFor(m => m.Country)
                </div>
            </div>*@
            <div class="control-group">
                @Html.LabelFor(x => x.Zip, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextBoxFor(x => x.Zip, new { placeholder = Html.DisplayNameFor(x => x.Zip), @class = "span12" })
                    @Html.ValidationMessageFor(m => m.Zip)
                </div>
            </div>
            @*<div class="control-group">
                <div class="controls">
                    @Html.CheckBoxFor(x => x.IsUseDirectory)
                    @Html.LabelFor(x => x.IsUseDirectory, new { @class = "lbl" })
                </div>
            </div>*@
    
            <h3 class="header smaller lighter green">Family members</h3>
    
            @Html.Partial("_FamilyPeoplesPartial", new FamilyPeoplesModel
            {
                Guardians = Model.Guardians,
                Students = Model.Students,
                FamilyGuardians = Model.FamilyGuardians,
                FamilyStudents = Model.FamilyStudents
            })
        }
    </div>
   @* <div class="span11">
        
        <h3 class="header smaller lighter green">Monthly contact log</h3>

        <div class="span11">
            <table id="gridTable"></table>
            <div id="gridPager"></div>
        </div>
    </div>*@
    <div class="span8">
        <div class="form-actions">
            <button onclick="javascript:$('#editFamilyForm').submit()" class="btn btn-success" type="button">
                <i class="icon-ok bigger-110"></i>
                Save Family
            </button>
            <button onclick="javascript:location.href='@Url.Action("Index")'" class="btn btn-info" type="button">
                <i class="icon-reply bigger-110"></i>
                Cancel
            </button>
        </div>
    </div>
</div>

<div class="row-fluid">
    
</div>

@section Styles {
    @Styles.Render("~/Content/css/jqGrid")
}

@section Scripts {
    @Scripts.Render("~/bundles/jqGrid")

    <script type="text/javascript">
        jQuery(function ($) {
            fpcs.family.initFamilyCreateEditPages();

            //var familyId = $("#familyId").val();
            //fpcs.monthlyContactLog.initIndexPage(familyId);
        });
    </script>

    @Scripts.Render("~/bundles/jqueryval")
}

FPCS.Web.Admin/Views/Family/_CreateMonthlyContactLog.cshtml
@model FPCS.Web.Admin.Models.Family.MonthlyContactLogCreateModel
@using FPCS.Web.Admin.Models.Family;

@{
    ViewBag.Title = "Monthly Contact Log Create Manager";
    ViewBag.Header = "Monthly Contact Log Create Manager";
    ViewBag.SubHeader = "Create Monthly Contact Log";
}

@section head{
}

<div class="row-fluid">
    <div class="span12">
    @using (Html.BeginForm("_CreateMonthlyContactLog", "Family", FormMethod.Post, new { id = "monthlyContactLogForm", @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(x => x.FamilyId)
        @Html.HiddenFor(x => x.TeacherId)

        <h3 class="header smaller lighter green">Main monthly contact log information</h3>

        <div class="controls">
            @Html.ValidationSummary(true)
        </div>

        <div class="control-group">
            @Html.LabelFor(x => x.Date, new { @class = "control-label" })
            <div class="controls">
                @Html.TextBoxFor(x => x.Date, "{0:MM/dd/yyyy}", new { placeholder = Html.DisplayNameFor(x => x.Date), @class = "span6 date-picker", data_date_format = "mm/dd/yyyy" })
                <span class="add-on">
                    <i class="icon-calendar"></i>
                </span>
                @Html.ValidationMessageFor(m => m.Date)
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(x => x.Comment, new { @class = "control-label" })
            <div class="controls">
                @Html.TextAreaFor(x => x.Comment, new { placeholder = Html.DisplayNameFor(x => x.Comment), @class = "autosize-transition span6" })
                @Html.ValidationMessageFor(m => m.Comment)
            </div>
        </div>
        <div class="form-actions">
            <button class="btn btn-success btn-save" type="button">
                <i class="icon-ok bigger-110"></i>
                Save log
            </button>
            <button class="btn btn-info btn-cancel" type="button">
                <i class="icon-reply bigger-110"></i>
                Cancel
            </button>
        </div>
        }
    </div>
</div>

FPCS.Web.Admin/Views/Family/_FamilyGuardianGuardianPartial.cshtml
@model FPCS.Web.Admin.Models.Family.LightGuardianModel

<div class="profile-activity clearfix">
    @Html.Hidden("FamilyGuardians.Index", Model.DbUserId)
    @Html.Hidden("FamilyGuardians[" + Model.DbUserId + "].DbUserId", Model.DbUserId)
    @Html.Hidden("FamilyGuardians[" + Model.DbUserId + "].FullName", Model.FullName)
    @Html.Hidden("FamilyGuardians[" + Model.DbUserId + "].CellPhone", Model.CellPhone)
    <div>
        <img class="pull-left" alt="Alex Doe's avatar" src="/Images/avatar2.png" />
        @Html.ActionLink(Model.FullName, "_Edit", "Guardian", new { id = Model.DbUserId, isDialog = true }, new { @class = "user editGuardianOpen" })
        @if(!String.IsNullOrEmpty(Model.CellPhone))
        {
            <div class="time">
                <i class="icon-phone  bigger-110"></i>
                @Model.CellPhone
            </div>
        }
    </div>

    <div class="tools action-buttons">
        <a rowid="@Model.DbUserId" href="#" class="blue editGuardianOpen">
            <i class="icon-pencil bigger-125"></i>
        </a>
    </div>
</div>