FPCS.Web.Admin/Controllers/InstructorController.cs
using FPCS.Core.jqGrid;
using FPCS.Data;
using FPCS.Data.Enums;
using FPCS.Data.Repo;
using FPCS.Web.Admin.Code;
using FPCS.Web.Admin.Models.Instructor;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FPCS.Core.Extensions;

namespace FPCS.Web.Admin.Controllers
{
    public class InstructorController : BaseController
    {
        [FPCSAuthorize(Role.Admin, Role.Teacher)]
        public ActionResult Index()
        {
            return View();
        }

        [FPCSAuthorize(Role.Admin, Role.Teacher)]
        public JsonResult _Index(GridOptions options, InstructorsListOptions instructorsListOptions)
        {
            using (var uow = UnityManager.Resolve<IUnitOfWork>())
            {
                var repo = uow.GetRepo<IStudentPacketCourseRepo>();

                var dbList = repo.GetByInstructor(Session.GetUser().Role == Role.Teacher ? Session.GetUser().UserId : Guid.Empty, SchoolYear.SchoolYearId)
                                 .Select(x => new
                {
                    StudentPacketCourseId = x.StudentPacketCourseId,
                    ClassName = x.FPCSCourse.Name,
                    StudentId = x.StudentPacket.Student.DbUserId,
                    LastName = x.StudentPacket.Student.LastName,
                    FirstName = x.StudentPacket.Student.FirstName,
                    GuardSign = x.GuardianSignature,
                    GuardComment = x.GuardianComment,
                    GuardName = x.Guardian != null ? x.Guardian.FirstName : String.Empty,
                    SponsorSign = x.SponsorSignature,
                    SponsorComment = x.SponsorComment,
                    SponsorName = x.Sponsor != null ? x.Sponsor.LastName : String.Empty,
                    InstructSign = x.InstructorSignature,
                    InstructComment = x.InstructorComment,
                    InstructName = x.Instructor != null ? x.Instructor.LastName : String.Empty,
                    AdminSign = x.AdminSignature,
                    AdminComment = x.AdminComment,
                    AdminName = x.Admin != null ? x.Admin.LastName : String.Empty,
                    FamilyId = x.StudentPacket.Student.Families.FirstOrDefault() != null ? 
                                x.StudentPacket.Student.Families.FirstOrDefault().FamilyId : 0,
                    FamilyEmail = x.StudentPacket.Student.Families.FirstOrDefault() != null ? 
                                    x.StudentPacket.Student.Families.FirstOrDefault().Email : String.Empty,
                    FamilyPhone = x.StudentPacket.Student.Families.FirstOrDefault() != null ? 
                                    x.StudentPacket.Student.Families.FirstOrDefault().Telephone : String.Empty,
                })
                .ToList();

                var dbListGuardian = uow.GetRepo<IGuardianRepo>()
                    .GetAll()
                    .Where(x => x.Families.FirstOrDefault(t => !t.IsDeleted) != null)
                    .Select(x => new
                    {
                        Name = x.FirstName,
                        FamilyId = x.Families.FirstOrDefault(t => !t.IsDeleted).FamilyId
                    })
                    .ToList();

                var result = dbList.Select(x => new InstructorMiniModel
                {
                    StudentPacketCourseId = x.StudentPacketCourseId,
                    ClassName = x.ClassName,
                    StudentName = String.Format(@"{0}, {1}", x.LastName, x.FirstName),
                    Guardians =
                        String.Join(@", ",
                            dbListGuardian.Where(t => t.FamilyId == x.FamilyId)
                                .Select(t => t.Name)),
                    Email = x.FamilyEmail,
                    FamilyPhone = x.FamilyPhone,
                    Comments = String.Format(@"Guardians: {0}<br />Sponsor: {1}<br />Instructor: {2}<br />Admin: {3}", x.GuardComment, x.SponsorComment, x.InstructComment, x.AdminComment),
                    GuardSign = x.GuardSign.HasValue ? String.Format(@"{0}<br />{1}", x.GuardSign.Value.GetDescription(), x.GuardName) : "not signed",
                    SponsorSign = x.SponsorSign.HasValue ? String.Format(@"{0}<br />{1}", x.SponsorSign.Value.GetDescription(), x.SponsorName) : "not signed",
                    InstructSign = x.InstructSign.HasValue ? String.Format(@"{0}<br />{1}", x.InstructSign.Value.GetDescription(), x.InstructName) : "not signed",
                    AdminSign = x.AdminSign.HasValue ? String.Format(@"{0}<br />{1}", x.AdminSign.Value.GetDescription(), x.AdminName) : "not signed"
                });

                return Json(result);
            }
        }
    }
}

FPCS.Web.Admin/Controllers/SharedController.cs
using System;
using System.Web.Mvc;

using FPCS.Data.Enums;
using FPCS.Web.Admin.Code;
using FPCS.Web.Admin.Models.Shared;

namespace FPCS.Web.Admin.Controllers
{
    public class SharedController : BaseController
    {
        public ActionResult _TopNavPartial()
        {
            var model = new TopNavModel();
            model.SessionSchoolYear = SchoolYear;
            model.SessionUser = User;
            model.Init();
            return PartialView(model);
        }

        [FPCSAuthorize()]
        public ActionResult SetSchoolYear(Int32 year)
        {
            var schoolYear = HttpContext.Session.SetSchoolYear(year);
            if (schoolYear == null)
            {
                if (User.Role == Role.Admin)
                    return RedirectToAction("Create", "SchoolYear", new { year = year });
                else
                    return Error("The year {0} wasn't initialized by administrator. Please contact with administrator or select another year.", year);
            }

            if (Request.UrlReferrer != null &&
                Request.UrlReferrer.AbsolutePath != Request.Url.AbsolutePath &&
                Request.UrlReferrer.Host == Request.Url.Host &&
                Request.UrlReferrer.AbsolutePath != "/SchoolYear/Create")
            {
                return Redirect(Request.UrlReferrer.OriginalString);
            }
            else if (Request.UrlReferrer != null &&
                Request.UrlReferrer.AbsolutePath != Request.Url.AbsolutePath &&
                Request.UrlReferrer.Host == Request.Url.Host &&
                Request.UrlReferrer.AbsolutePath == "/SchoolYear/Create")
            {
                return RedirectToAction("Index", "SchoolYear");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

FPCS.Web.Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using FPCS.Core.jqGrid;
using FPCS.Core.Extensions;
using FPCS.Data;
using FPCS.Data.Enums;
using FPCS.Data.Repo;
using FPCS.Web.Admin.Code;
using FPCS.Web.Admin.Models.User;
using FPCS.Core;
using FPCS.Data.Entities;

namespace FPCS.Web.Admin.Controllers
{
    [FPCSAuthorize(Role.Admin, Role.Guardian, Role.Teacher)]
    public class UserController : BaseController
    {
        public ActionResult Index()
        {
            UserIndexModel model = new UserIndexModel();

            model.IsLocked = "true:True;false:False";
            model.Roles = String.Format(@"{0}:{1};", ((Int32)Role.Admin).ToString(), Role.Admin.GetDescription()) +
                String.Format(@"{0}:{1};", ((Int32)Role.Teacher).ToString(), Role.Teacher.GetDescription()) +
                String.Format(@"{0}:{1}", ((Int32)Role.Guardian).ToString(), Role.Guardian.GetDescription());

            return View(model);
        }

        public JsonResult _Index(GridOptions options, UsersListOptions usersListOptions)
        {
            using (var uow = UnityManager.Resolve<IUnitOfWork>())
            {
                var role = usersListOptions.Role;
                var isLocked = usersListOptions.IsLocked;

                var dbList = uow.GetRepo<IDbUserRepo>()
                                .GetByRoles(SchoolYear.SchoolYearId, Role.Admin, Role.Guardian, Role.Teacher)
                                .Where(x => ((role.HasValue && x.Role == role.Value) || !role.HasValue) &&
                                            ((isLocked.HasValue && x.IsLocked == isLocked.Value) || !isLocked.HasValue));

                var engine = new GridDynamicEngine(options, usersListOptions);

                usersListOptions.IsLocked = null;
                usersListOptions.Role = null;

                var result = engine.ApplyAll(dbList, x => new UserMiniModel
                {
                    DbUserId = x.DbUserId,
                    FullName = x.LastName + ", " + x.FirstName,
                    Email = x.Email,
                    IsLocked = x.IsLocked ? "Locked" : "Not Locked",
                    Role = x.Role
                });

                return Json(result);
            }
        }
        
        [HttpGet]
        public ActionResult _Details(Guid id)
        {
            using (var uow = UnityManager.Resolve<IUnitOfWork>())
            {
                var dbEntity = uow.GetRepo<IDbUserRepo>().Get(id);
                if (dbEntity == null) return ErrorPartial("User {0} not found", id);

                var model = new UserDetailsModel
                {
                    DbUserId = dbEntity.DbUserId,
                    FullName = dbEntity.FullName,
                    Email = dbEntity.Email,
                    Login = dbEntity.Login,
                    Role = dbEntity.Role.GetDescription(),
                    IsLocked = dbEntity.IsLocked
                };

                return PartialView(model);
            }
        }

        [HttpGet]
        public ActionResult _Create()
        {
            using (var uow = UnityManager.Resolve<IUnitOfWork>())
            {
                var model = new UserCreateModel
                {
                    FirstName = String.Empty,
                    LastName = String.Empty,
                    MiddleInitial = String.Empty,
                    Email = String.Empty,
                    Login = String.Empty,
                    Role = Role.Admin.GetDescription()
                };

                return PartialView(model);
            }
        }

        [HttpPost]
        public ActionResult _Create(UserCreateModel model)
        {
            if (model.IsSendEmail && (String.IsNullOrEmpty(model.Password) || String.IsNullOrEmpty(model.Email)))
            {
                ModelState.AddModelError("", "If you want send Email to user, please enter email address and password");
                if (String.IsNullOrEmpty(model.Password)) ModelState.AddModelError("Password", "*");
                if (String.IsNullOrEmpty(model.Email)) ModelState.AddModelError("Email", "*");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    using (var uow = UnityManager.Resolve<IUnitOfWork>())
                    {
                        var repo = uow.GetRepo<IAdminRepo>();
                        var dbEntity = repo.Add(model.Login, model.Password, model.Email, model.FirstName, model.LastName, model.MiddleInitial);
                        uow.Commit();

                        if (model.IsSendEmail)
                        {
                            var subject = "Your account on FPCS was activated";
                            var body = "Your account on FPCS was activated. Your credentials:\r\n";
                            body += String.Format("Login: {0}\r\nPassword: {1}", model.Login, model.Password);
                            EmailSender.Instance.Send(dbEntity.Email, subject, body);
                        }

                        return JsonRes(dbEntity.DbUserId.ToString());
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            return PartialView(model);
        }

        [HttpGet]
        public ActionResult _Edit(Guid id)
        {
            using (var uow = UnityManager.Resolve<IUnitOfWork>())
            {
                var dbEntity = uow.GetRepo<IDbUserRepo>().Get(id);
                if (dbEntity == null) return ErrorPartial("User {0} not found", id);

                var model = new UserEditModel
                {
                    DbUserId = dbEntity.DbUserId,
                    FullName = dbEntity.FullName,
                    Email = dbEntity.Email,
                    Login = dbEntity.Login,
                    Role = dbEntity.Role.GetDescription(),
                    IsLocked = dbEntity.IsLocked
                };

                return PartialView(model);
            }
        }

        [HttpPost]
        public ActionResult _Edit(UserEditModel model)
        {
            if (model.IsSendEmail && (String.IsNullOrEmpty(model.Password) || String.IsNullOrEmpty(model.Email)))
            {
                ModelState.AddModelError("", "If you want send Email to user, please enter email address and password");
                if (String.IsNullOrEmpty(model.Password)) ModelState.AddModelError("Password", "*");
                if (String.IsNullOrEmpty(model.Email)) ModelState.AddModelError("Email", "*");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    using (var uow = UnityManager.Resolve<IUnitOfWork>())
                    {
                        var repo = uow.GetRepo<IDbUserRepo>();
                        var dbEntity = repo.Update(model.DbUserId, model.Email, model.Login, model.Password, model.IsLocked);
                        uow.Commit();

                        if (model.IsSendEmail)
                        {
                            var subject = "Your account on FPCS was activated";
                            var body = "Your account on FPCS was activated. Your credentials:\r\n";
                            body += String.Format("Login: {0}\r\nPassword: {1}", model.Login, model.Password);
                            EmailSender.Instance.Send(dbEntity.Email, subject, body);
                        }

                        return JsonRes(dbEntity.DbUserId.ToString());
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            return PartialView(model);
        }

        [HttpGet]
        public ActionResult ProfileDetails()
        {
            using (var uow = UnityManager.Resolve<IUnitOfWork>())
            {
                var repo = uow.GetRepo<IDbUserRepo>();
                Guid dbUserId = User.UserId;

                DbUser dbUser = repo.Get(dbUserId);

                ProfileDetailsModel model = new ProfileDetailsModel(dbUser);

                return View(model);
            }
        }

        [HttpGet]
        public ActionResult ProfileEdit()
        {
            using (var uow = UnityManager.Resolve<IUnitOfWork>())
            {
                var repo = uow.GetRepo<IDbUserRepo>();
                Guid dbUserId = User.UserId;

                DbUser dbUser = repo.Get(dbUserId);

                ProfileEditModel model = new ProfileEditModel(dbUser);

                return View(model);
            }
        }

        [HttpPost]
        public ActionResult ProfileEdit(ProfileEditModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    using (var uow = UnityManager.Resolve<IUnitOfWork>())
                    {
                        var repo = uow.GetRepo<IDbUserRepo>();
                        var dbEntity = repo.Get(model.DbUserId);

                        dbEntity.FirstName = model.FirstName.TrimAndReduce();
                        dbEntity.LastName = model.LastName.TrimAndReduce();
                        dbEntity.MiddleInitial = model.MI.TrimAndReduce();
                        dbEntity.FullName = String.Format(@"{0}, {1}", model.LastName.TrimAndReduce(), model.FirstName.TrimAndReduce());
                        dbEntity.Email = model.Email.TrimAndReduce();
                        dbEntity.Login = model.Login;
                        dbEntity.Password = model.Password;
                        dbEntity.UpdatedDate = DateTimeOffset.Now;

                        repo.Update(dbEntity);

                        uow.Commit();

                        return RedirectToAction("ProfileDetails");
                    }

FPCS.Web.Admin/Views/Shared/_BreadcrumbPartial.cshtml
<div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
        try { ace.settings.check('breadcrumbs', 'fixed') } catch (e) { }
    </script>

    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="#">Home</a>

            <span class="divider">
                <i class="icon-angle-right arrow-icon"></i>
            </span>
        </li>
        <li class="active">Dashboard</li>
    </ul>
    <!--.breadcrumb-->

    <div class="nav-search" id="nav-search">
        <form class="form-search">
            <span class="input-icon">
                <input type="text" placeholder="Search ..." class="input-small nav-search-input" id="nav-search-input" autocomplete="off" />
                <i class="icon-search nav-search-icon"></i>
            </span>
        </form>
    </div>
    <!--#nav-search-->
</div>

FPCS.Web.Admin/Views/Shared/_ErrorPartial.cshtml
@model String

@{
    ViewBag.Title = "Error";
}

<hgroup class="title">
    <h2 class="error">@Model</h2>
</hgroup>

FPCS.Web.Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - FPCS</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!--basic styles-->
    @Styles.Render("~/Content/css/bootstrap")
    
    <!--[if IE 7]>
		  <link rel="stylesheet" href="/Content/css/font-awesome-ie7.min.css" />
		<![endif]-->

    <!--page specific plugin styles-->
    @Styles.Render("~/Content/css/plugin")

    @RenderSection("styles", required: false)

    <!--ace styles-->

    @Styles.Render("~/Content/css/ace")

    <!--[if lte IE 8]>
		  <link rel="stylesheet" href="/Content/css/ace-ie.min.css" />
		<![endif]-->

    @Styles.Render("~/Content/css/ace")
    @Styles.Render("~/Content/css/site")
    
    <!--ace settings handler-->

    <script src="/Scripts/ace-extra.min.js"></script>

    @RenderSection("head", required: false)
</head>
<body>
    @Html.Hidden("roleCurrentUser", Html.GetRoleCurrentUser(), new { id = "roleCurrentUser" })
    @Html.Hidden("idCurrentUser", Html.GetUser().UserId, new { id = "idCurrentUser" })

    <div class="navbar" id="navbar">
        <script type="text/javascript">
            try { ace.settings.check('navbar', 'fixed') } catch (e) { }
        </script>

        <div class="navbar-inner">
            <div class="container-fluid">
                <a href="@Url.Action("Index", "Home")" class="brand">
                    <small>
                        <i class="icon-leaf"></i>
                        FPCS @Html.GetRoleCurrentUserString()
                    </small>
                </a>
                <!--/.brand-->

                @Html.Action("_TopNavPartial", "Shared")
            </div>
            <!--/.container-fluid-->
        </div>
        <!--/.navbar-inner-->
    </div>

    <div class="main-container container-fluid">
        <a class="menu-toggler" id="menu-toggler" href="#">
            <span class="menu-text"></span>
        </a>

        @Html.Partial("_SidebarPartial")

        <div class="main-content">

            <div class="main-alert alert alert-block" style="display:none">
                <button data-dismiss="alert" class="close" type="button">
                    <i class="icon-remove"></i>
                </button>
                <i class="icon-bullhorn"></i>
                <span class="main-alert-text"></span>
            </div>

            <div class="page-content">
                @if (ViewBag.Header != null)
                {
                    <div class="page-header position-relative">
                        <h1>
                            @ViewBag.Header
                            &nbsp;
                            @if (ViewBag.SubHeader != null)
                            {
                                <small>
                                    <i class="icon-double-angle-right"></i>
                                    @ViewBag.SubHeader
                                </small>
                            }
                        </h1>
                    </div>
                    <!--/.page-header-->
                }

                @RenderBody()
            </div>
            <!--/.page-content-->

           @Html.Partial("_SettingsPartial")
        </div>
        <!--/.main-content-->
    </div>
    <!--/.main-container-->

    <!--#dialog-message-->
    <div id="dialog-message" class="hide"></div>

    <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-small btn-inverse">
        <i class="icon-double-angle-up icon-only bigger-110"></i>
    </a>

    <!--basic scripts-->

    @Scripts.Render("~/bundles/jquery")

    <script type="text/javascript">
        if ("ontouchend" in document) document.write("<script src='/Scripts/jquery.mobile.custom.min.js'>" + "<" + "/script>");
    </script>

    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jquery-migrate")

    <!--page specific plugin scripts-->

    @Scripts.Render("~/bundles/bootstrap-tag")
    @Scripts.Render("~/bundles/bootstrap-wysiwyg")
    @Scripts.Render("~/bundles/jquery-hotkeys")
    @Scripts.Render("~/bundles/jquery-ui")
    @Scripts.Render("~/bundles/jquery-slimscroll")
    @Scripts.Render("~/bundles/bootstrap-datetimepicker")
    @Scripts.Render("~/bundles/jquery-autosize")
    @Scripts.Render("~/bundles/chosen-jquery")
    @Scripts.Render("~/bundles/maskedinput")
    @Scripts.Render("~/bundles/select2-jquery")
    @Scripts.Render("~/bundles/fuelux-spinner")
    @Scripts.Render("~/bundles/jquery-scrolltable")
    @Scripts.Render("~/bundles/jquery-alerts")
    
<!--ace scripts-->
    @Scripts.Render("~/bundles/ace")
    
    <!--editable scripts-->
    @Scripts.Render("~/bundles/editable")

    <!--inline scripts related to this page-->
    @Scripts.Render("~/bundles/fpcs")
    
    <script type="text/javascript">
        jQuery(function ($) {
            fpcs.initTitleForDialog();
            fpcs.topNav.initSchoolYear();
            @if(ViewBag.Message != null)
            {
                @:fpcs.showMessage("@ViewBag.Message");
            }
        });
    </script>

    @RenderSection("scripts", required: false)
    
    <div id="shadow" class="shadow_popup" style="display:none">

    </div>

    <div id="loader" class="popup" style="display:none">
        <img src="~/Content/images/ajax-loader.gif" width="100%" height="100%" />
    </div>
</body>
</html>

FPCS.Web.Admin/Views/Shared/_SidebarPartial.cshtml
@using FPCS.Data.Enums;

<div class="sidebar" id="sidebar">
    <script type="text/javascript">
        try { ace.settings.check('sidebar', 'fixed') } catch (e) { }
    </script>

    @*<div class="sidebar-shortcuts" id="sidebar-shortcuts">
        <div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
            <button class="btn btn-small btn-success">
                <i class="icon-signal"></i>
            </button>

            <button class="btn btn-small btn-info">
                <i class="icon-pencil"></i>
            </button>

            <button class="btn btn-small btn-warning">
                <i class="icon-group"></i>
            </button>

            <button class="btn btn-small btn-danger">
                <i class="icon-cogs"></i>
            </button>
        </div>

        <div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
            <span class="btn btn-success"></span>

            <span class="btn btn-info"></span>

            <span class="btn btn-warning"></span>

            <span class="btn btn-danger"></span>
        </div>
    </div>
    <!--#sidebar-shortcuts-->*@

    <ul class="nav nav-list">
        <li>
            <a href="@Url.Action("Index", "Home")">
                <i class="icon-dashboard"></i>
                <span class="menu-text">Dashboard </span>
            </a>
        </li>

        @if (Html.IsAccessEnabled(Role.Admin, Role.Teacher))
        {
            <li>
                <a href="@Url.Action("Index", "Family")">
                    <i class="icon-group"></i>
                    <span class="menu-text">Family Manager</span>
                </a>
            </li>
        }

        @*@if (Html.IsAccessEnabled(Role.Guardian))
        {
            <li>
                <a href="@Url.Action("DetailsForGuardian", "Family")">
                    <i class="icon-group"></i>
                    <span class="menu-text">Family Manager</span>
                </a>
            </li>
        }*@

        @if (Html.IsAccessEnabled(Role.Admin, Role.Teacher, Role.Guardian))
        {
            <li>
                <a href="@Url.Action("Index", "Guardian")">
                    <i class="icon-group"></i>
                    <span class="menu-text">Guardian Manager </span>
                </a>
            </li>
        }

        @if (Html.IsAccessEnabled(Role.Admin))
        {
            <li>
                <a href="@Url.Action("Index", "Student")">
                    <i class="icon-group"></i>
                    <span class="menu-text">Student Manager </span>
                </a>
            </li>
        }

        @if (Html.IsAccessEnabled(Role.Admin))
        {
            <li>
                <a href="@Url.Action("Index", "Teacher")">
                    <i class="icon-group"></i>
                    <span class="menu-text">Teacher Manager </span>
                </a>
            </li>
        }
            
        @*@if (Html.IsAccessEnabled(Role.Admin, Role.Teacher))
        {
            <li>
                <a href="@Url.Action("Index", "Instructor")">
                    <i class="icon-group"></i>
                    <span class="menu-text">Instructor Manager</span>
                </a>
            </li>
        }*@
        
        @*@if (Html.IsAccessEnabled(Role.Admin, Role.Teacher, Role.Guardian))
        {
            <li>
                <a href="@Url.Action("Index", "Grade")">
                    <i class="icon-group"></i>
                    <span class="menu-text">Grade Manager</span>
                </a>
            </li>
        }

        @if (Html.IsAccessEnabled(Role.Admin, Role.Teacher, Role.Guardian))
        {
            <li>
                <a href="@Url.Action("Index", "SignedCourse")">
                    <i class="icon-calendar"></i>
                    <span class="menu-text">Signed Course</span>
                </a>
            </li>
        }*@
            
        @if (Html.IsAccessEnabled(Role.Admin, Role.Teacher))
        {
            <li>
                <a href="@Url.Action("Index", "FPCSCourse")">
                    <i class="icon-briefcase"></i>
                    <span class="menu-text">FPCS Course Manager </span>
                </a>
            </li>
            
            <li>
                <a href="@Url.Action("Index", "ILPBank")">
                    <i class="icon-briefcase"></i>
                    <span class="menu-text">ILP Bank Manager </span>
                </a>
            </li>
        }

        @if (Html.IsAccessEnabled(Role.Admin, Role.Guardian, Role.Teacher))
        {
            <li>
                <a href="@Url.Action("Index", "Vendor")">
                    <i class="icon-calendar"></i>
                    <span class="menu-text">Vendor Manager</span>
                </a>
            </li>
        }

        @if (Html.IsAccessEnabled(Role.Admin))
        {
            <li>
                <a href="@Url.Action("Index", "SignedPacket")">
                    <i class="icon-calendar"></i>
                    <span class="menu-text">Signed Packet</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index", "ASDCourse")">
                    <i class="icon-briefcase"></i>
                    <span class="menu-text">ASD Course Manager </span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index", "SchoolYear")">
                    <i class="icon-calendar"></i>
                    <span class="menu-text">School Year Manager </span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index", "GoodAndServiceApproval")">
                    <i class="icon-calendar"></i>
                    <span class="menu-text">Good and Service</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index", "User")">
                    <i class="icon-group"></i>
                    <span class="menu-text">User Manager</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Subject")">
                    <i class="icon-group"></i>
                    <span class="menu-text">Subject Manager</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Import")">
                    <i class="icon-group"></i>
                    <span class="menu-text">Import Manager</span>
                </a>
            </li>
        }
        
        @if (Html.IsAccessEnabled(Role.Admin, Role.Guardian, Role.Teacher))
        {
            <li>
                <a href="@Url.Action("ProfileDetails", "User")">
                    <i class="icon-group"></i>
                    <span class="menu-text">Profile User</span>
                </a>
            </li>
        }
    </ul>
    <!--/.nav-list-->

    <div class="sidebar-collapse" id="sidebar-collapse">
        <i class="icon-double-angle-left" data-icon1="icon-double-angle-left" data-icon2="icon-double-angle-right"></i>
    </div>

    <script type="text/javascript">
        try { ace.settings.check('sidebar', 'collapsed') } catch (e) { }
    </script>
</div>