FPCS.Web.Admin/Models/Subject/SubjectCreateModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;

using FPCS.Core.Unity;
using FPCS.Data;
using FPCS.Data.Repo;

namespace FPCS.Web.Admin.Models.Subject
{
    public class SubjectCreateModel
    {
        [Required]
        [Display(Name = "Name")]
        public String Name { get; set; }

        [Display(Name = "Description")]
        public String Description { get; set; }
        
        [Required]
        [Display(Name = "Subject is elective")]
        public Boolean IsElective { get; set; }

        public void Init()
        {
        }
    }
}

FPCS.Web.Admin/Models/Subject/SubjectDetailsModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace FPCS.Web.Admin.Models.Subject
{
    public class SubjectDetailsModel
    {
        [Display(Name = "SubjectId")]
        public Int32 SubjectId { get; set; }

        [Display(Name = "Name")]
        public String Name { get; set; }

        [Display(Name = "Description")]
        public String Description { get; set; }

        [Display(Name = "Subject is elective")]
        public Boolean IsElective { get; set; }
    }
}

FPCS.Web.Admin/Models/Subject/SubjectEditModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;

using FPCS.Core.Unity;
using FPCS.Data;
using FPCS.Data.Repo;

namespace FPCS.Web.Admin.Models.Subject
{
    public class SubjectEditModel
    {
        [Required]
        [Display(Name = "SubjectId")]
        public Int32 SubjectId { get; set; }

        [Required]
        [Display(Name = "Name")]
        public String Name { get; set; }

        [Display(Name = "Description")]
        public String Description { get; set; }

        [Required]
        [Display(Name = "Subject is elective")]
        public Boolean IsElective { get; set; }

        public void Init()
        {
        }
    }
}

FPCS.Web.Admin/Models/Subject/SubjectListOptions.cs
using System;

using FPCS.Core.jqGrid;

namespace FPCS.Web.Admin.Models.Subject
{
    public class SubjectListOptions
    {
        [GridProperty(ExtensionType.All, true)]
        public Int32? SubjectId { get; set; }

        [GridProperty(ExtensionType.All, true, FilterOperation.Contains)]
        public String Name { get; set; }

        [GridProperty(ExtensionType.Filter, false)]
        [GridProperty(ExtensionType.All, true)]
        public String IsElective { get; set; }
    }
}

FPCS.Web.Admin/Models/Subject/SubjectMiniModel.cs
using System;

namespace FPCS.Web.Admin.Models.Subject
{
    public class SubjectMiniModel
    {
        public Int32 SubjectId { get; set; }

        public String Name { get; set; }

        public String IsElective { get; set; }
    }
}

FPCS.Web.Admin/Controllers/SubjectController.cs
using System;
using System.Linq;
using System.Web.Mvc;

using FPCS.Core.jqGrid;
using FPCS.Core.Extensions;

using FPCS.Data;
using FPCS.Data.Repo;
using FPCS.Data.Enums;
using FPCS.Data.Exceptions;
using FPCS.Web.Admin.Code;
using FPCS.Data.Entities;
using FPCS.Web.Admin.Models.Subject;

namespace FPCS.Web.Admin.Controllers
{
    public class SubjectController : BaseController
    {
        [FPCSAuthorize(Role.Admin)]
        public ActionResult Index()
        {
            return View();
        }

        [FPCSAuthorize(Role.Admin)]
        public JsonResult _Index(GridOptions options, SubjectListOptions coursesListOptions)
        {
            using (var uow = UnityManager.Resolve<IUnitOfWork>())
            {
                var repo = uow.GetRepo<ISubjectRepo>();
                var dbList = repo.GetAll();

                var engine = new GridDynamicEngine(options, coursesListOptions);
                var result = engine.ApplyAll(dbList, x => new SubjectMiniModel
                {
                    SubjectId = x.SubjectId,
                    Name = x.Name,
                    IsElective = x.IsElective ? "Elective" : "Core"
                });

                return Json(result);
            }
        }


        [HttpGet]
        [FPCSAuthorize(Role.Admin, Role.Teacher)]
        public PartialViewResult _Details(Int32 id)
        {
            using (var uow = UnityManager.Resolve<IUnitOfWork>())
            {
                var repo = uow.GetRepo<ISubjectRepo>();
                var dbEntity = repo.Get(id);
                if (dbEntity == null) return ErrorPartial("Subject {0} not found", id);

                var model = new SubjectDetailsModel
                {
                    SubjectId = dbEntity.SubjectId,
                    Name = dbEntity.Name,
                    IsElective = dbEntity.IsElective,
                    Description = dbEntity.Description
                };

                return PartialView(model);
            }
        }


        [HttpGet]
        [FPCSAuthorize(Role.Admin)]
        public PartialViewResult _Create()
        {
            var model = new SubjectCreateModel();
            model.Init();
            return PartialView(model);
        }

        [HttpPost]
        [FPCSAuthorize(Role.Admin)]
        [ValidateAntiForgeryToken]
        public ActionResult _Create(SubjectCreateModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    using (var uow = UnityManager.Resolve<IUnitOfWork>())
                    {
                        var repo = uow.GetRepo<ISubjectRepo>();
                        Subject dbEntity = new Subject();

                        dbEntity.Name = model.Name.TrimAndReduce();
                        dbEntity.Description = model.Description.TrimAndReduce();
                        dbEntity.IsElective = model.IsElective;
                        dbEntity.IsDeleted = false;

                        uow.Commit();

                        return JsonRes(dbEntity.SubjectId.ToString());
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            model.Init();
            return PartialView(model);
        }


        [HttpGet]
        [FPCSAuthorize(Role.Admin)]
        public PartialViewResult _Edit(Int32 id)
        {
            using (var uow = UnityManager.Resolve<IUnitOfWork>())
            {
                var repo = uow.GetRepo<ISubjectRepo>();
                var dbEntity = repo.Get(id);
                if (dbEntity == null) return ErrorPartial("Subject {0} not found", id);

                var model = new SubjectEditModel
                {
                    SubjectId = dbEntity.SubjectId,
                    Name = dbEntity.Name,
                    Description = dbEntity.Description,
                    IsElective = dbEntity.IsElective
                };

                model.Init();
                return PartialView(model);
            }
        }

        [HttpPost]
        [FPCSAuthorize(Role.Admin)]
        [ValidateAntiForgeryToken]
        public ActionResult _Edit(SubjectEditModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    using (var uow = UnityManager.Resolve<IUnitOfWork>())
                    {
                        var repo = uow.GetRepo<ISubjectRepo>();

                        Subject dbEntity = repo.Get(model.SubjectId);

                        if (dbEntity == null) return ErrorPartial("Subject {0} not found", model.SubjectId);

                        dbEntity.Name = model.Name.TrimAndReduce();
                        dbEntity.Description = model.Description.TrimAndReduce();
                        dbEntity.IsElective = model.IsElective;
                        dbEntity.IsDeleted = false;

                        uow.Commit();

                        return JsonRes(dbEntity.SubjectId.ToString());
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            model.Init();
            return PartialView(model);
        }


        [HttpPost]
        [FPCSAuthorize(Role.Admin)]
        public ActionResult Delete(Int32 id)
        {
            try
            {
                using (var uow = UnityManager.Resolve<IUnitOfWork>())
                {
                    var repo = uow.GetRepo<ISubjectRepo>();
                    repo.Remove(id);

                    uow.Commit();
                    return JsonRes();
                }
            }
            catch (Exception ex)
            {
                return JsonRes(Status.Error, ex.Message);
            }
        }

        [HttpPost]
        [FPCSAuthorize(Role.Admin)]
        public ActionResult DeleteAll(String id)
        {
            try
            {
                if (String.IsNullOrEmpty(id)) return JsonRes(Status.Error, "Not correct ids");

                var ids = id.Split(',');
                using (var uow = UnityManager.Resolve<IUnitOfWork>())
                {
                    Int32 errorsCount = 0;
                    var repo = uow.GetRepo<ISubjectRepo>();
                    foreach (var item in ids)
                    {
                        try
                        {
                            repo.Remove(Int32.Parse(item));
                        }
                        catch (Exception)
                        {
                            errorsCount++;
                        }
                    }

                    uow.Commit();
                    if (errorsCount == 0) return JsonRes(); 
                    else return JsonRes(Status.Error, "Were deleted not all entities");
                }
            }
            catch (Exception ex)
            {
                return JsonRes(Status.Error, ex.Message);
            }
        }
    }
}

FPCS.Web.Admin/Views/Subject/Index.cshtml
@{
    ViewBag.Title = "Subject Manager";
    ViewBag.Header = "Subject Manager";
}

<div class="row-fluid">
    <div class="span12 gridWrapper">
        <table id="gridTable"></table>
        <div id="gridPager"></div>
    </div>
</div>

@section Styles {
    @Styles.Render("~/Content/css/jqGrid")
}

@section Scripts {
    @Scripts.Render("~/bundles/jqGrid")

    <script type="text/javascript">
        jQuery(function ($) {
            fpcs.subject.initIndexPage();
        });
    </script>
}

FPCS.Web.Admin/Views/Subject/_Create.cshtml
@model FPCS.Web.Admin.Models.Subject.SubjectCreateModel

<div class="row-fluid">
    <div class="span12 ">

        @using (Html.BeginForm("_Create", "Subject", FormMethod.Post, new { id = "createSubjectForm", @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
   
            <div class="control-group">
                <div class="controls">
                    <h3 class="lighter block green">Fill following form to add new subject</h3>
                </div>
            </div>
    
            <div class="controls">
                @Html.ValidationSummary(true)
            </div>
    
            <div class="control-group">
                @Html.LabelFor(x => x.Name, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextBoxFor(x => x.Name, new { placeholder = Html.DisplayNameFor(x => x.Name), @class = "span8" })
                    @Html.ValidationMessageFor(m => m.Name)
                </div>
            </div>
            <div class="control-group">
                @Html.LabelFor(x => x.Description, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextAreaFor(x => x.Description, new { placeholder = Html.DisplayNameFor(x => x.Description), @class = "span8" })
                    @Html.ValidationMessageFor(m => m.Description)
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <div class="span8">
                        @Html.CheckBoxFor(x => x.IsElective)
                        @Html.LabelFor(x => x.IsElective, new { @class = "lbl" })
                        @Html.ValidationMessageFor(m => m.IsElective)
                    </div>
                </div>
            </div>
    
            <div class="form-actions">
                <button class="btn btn-success createSubjectSend" type="button">
                    <i class="icon-ok bigger-110"></i>
                    Save subject
                </button>
                <button onclick="javascript:fpcs.closeDialog()" class="btn btn-info" type="button">
                    <i class="icon-reply bigger-110"></i>
                    Cancel
                </button>
            </div>
        }

    </div>
</div>

@Html.Script(Scripts.Render("~/bundles/jqueryval"))

FPCS.Web.Admin/Views/Subject/_Details.cshtml
@model FPCS.Web.Admin.Models.Subject.SubjectDetailsModel

<div class="row-fluid form-horizontal">
    <div class="span12 ">

        <div class="control-group">
            <div class="controls">
                <h3 class="lighter block green">Subject Information</h3>
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(x => x.Name, new { @class = "control-label" })
            <div class="controls">
                @Html.TextBoxFor(x => x.Name, new { @class = "span8", @readonly = "true" })
                @Html.ValidationMessageFor(m => m.Name)
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(x => x.Description, new { @class = "control-label" })
            <div class="controls">
                @Html.TextAreaFor(x => x.Description, new { @class = "span8", @readonly = "true" })
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <div class="span8">
                    @Html.CheckBoxFor(x => x.IsElective, new { @readonly = "true", disabled = "true" })
                    @Html.LabelFor(x => x.IsElective, new { @class = "lbl" })
                </div>
            </div>
        </div>

        <div class="form-actions">
            <button onclick="javascript:fpcs.closeDialog()" class="btn btn-info" type="button">
                <i class="icon-reply bigger-110"></i>
                Close
            </button>
        </div>
    </div>
</div>

FPCS.Web.Admin/Views/Subject/_Edit.cshtml
@model FPCS.Web.Admin.Models.Subject.SubjectEditModel

<div class="row-fluid">
    <div class="span12 ">

        @using (Html.BeginForm("_Edit", "Subject", FormMethod.Post, new { id = "editSubjectForm", @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
   
            <div class="control-group">
                <div class="controls">
                    <h3 class="lighter block green">On this page you can edit the subject</h3>
                </div>
            </div>
    
            <div class="controls">
                @Html.ValidationSummary(true)
            </div>
    
            @Html.HiddenFor(x => x.SubjectId)

            <div class="control-group">
                @Html.LabelFor(x => x.Name, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextBoxFor(x => x.Name, new { placeholder = Html.DisplayNameFor(x => x.Name), @class = "span8" })
                    @Html.ValidationMessageFor(m => m.Name)
                </div>
            </div>
            <div class="control-group">
                @Html.LabelFor(x => x.Description, new { @class = "control-label" })
                <div class="controls">
                    @Html.TextAreaFor(x => x.Description, new { placeholder = Html.DisplayNameFor(x => x.Description), @class = "span8" })
                    @Html.ValidationMessageFor(m => m.Description)
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <div class="span8">
                        @Html.CheckBoxFor(x => x.IsElective)
                        @Html.LabelFor(x => x.IsElective, new { @class = "lbl" })
                        @Html.ValidationMessageFor(m => m.IsElective)
                    </div>
                </div>
            </div>
    
            <div class="form-actions">
                <button class="btn btn-success editSubjectSend" type="button">
                    <i class="icon-ok bigger-110"></i>
                    Save subject
                </button>
                <button onclick="javascript:fpcs.closeDialog()" class="btn btn-info" type="button">
                    <i class="icon-reply bigger-110"></i>
                    Cancel
                </button>
            </div>
        }

    </div>
</div>

@Html.Script(Scripts.Render("~/bundles/jqueryval"))