FPCS.Web.Admin/Models/StudentPacket2/AgreementModel.cs
using FPCS.Core.Unity;
using FPCS.Data;
using DEB = FPCS.Data.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using FPCS.Data.Repo;

namespace FPCS.Web.Admin.Models.StudentPacket2
{
    public class AgreementModel
    {
        public Guid StudentId { get; set; }

        public String StudentName {get;set;}

        public Boolean IsASDTASigned { get; set; }

        public Boolean IsPRASigned { get; set; }

        public String ASDTAGuardianSigner { get; set; }

        public String PRAGuardianSigner { get; set; }

        public List<AgreementModel> Students { get; set; }

        public void Init(Int64 studentPacketId)
        {
            using (var uow = UnityManager.Instance.Resolve<IUnitOfWork>())
            {
                DEB.StudentPacket packet = uow.GetRepo<IStudentPacketRepo>().Get(studentPacketId);

                if (packet == null) { throw new Exception("Student packet not found"); }

                StudentId = packet.StudentId;
                StudentName = String.Format(@"{0}, {1}", packet.Student.LastName, packet.Student.FirstName);
                IsASDTASigned = packet.IsASDTASigned;
                IsPRASigned = packet.IsPRASigned;
                ASDTAGuardianSigner = packet.ASDTAGuardian != null ? String.Format(@"{0}, {1}", packet.ASDTAGuardian.LastName, packet.ASDTAGuardian.FirstName) : String.Empty;
                PRAGuardianSigner = packet.PRAGuardian != null ? String.Format(@"{0}, {1}", packet.PRAGuardian.LastName, packet.PRAGuardian.FirstName) : String.Empty;

                Int64 familyId = 0;
                if (packet.Student.Families.FirstOrDefault() == null) { return; }

                familyId = packet.Student.Families.FirstOrDefault().FamilyId;

                var studentIds = uow.GetRepo<IStudentRepo>()
                                    .GetByFamily(familyId, packet.SchoolYearId)
                                    .Select(x => x.DbUserId)
                                    .ToList();

                Students = uow.GetRepo<IStudentPacketRepo>()
                              .GetAll()
                              .Where(x => studentIds.Contains(x.StudentId))
                              .Select(x => new AgreementModel()
                              {
                                  StudentId = x.StudentId,
                                  StudentName = x.Student.LastName + ", " + x.Student.FirstName,
                                  IsASDTASigned = x.IsASDTASigned,
                                  IsPRASigned = x.IsPRASigned,
                                  ASDTAGuardianSigner = x.ASDTAGuardian != null ?
                                                          x.ASDTAGuardian.LastName + ", " + x.ASDTAGuardian.FirstName :
                                                          String.Empty,
                                  PRAGuardianSigner = x.PRAGuardian != null ?
                                                          x.PRAGuardian.LastName + ", " + x.PRAGuardian.FirstName :
                                                          String.Empty
                              })
                              .ToList();
            }
        }
    }
}

FPCS.Web.Admin/Models/StudentPacket2/AmpElaModel.cs
using System;
using System.Linq;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;

using FPCS.Core.Unity;
using FPCS.Core.Extensions;
using FPCS.Data;
using FPCS.Data.Repo;
using FPCS.Data.Enums;

namespace FPCS.Web.Admin.Models.StudentPacket2
{
    public class AmpElaModel
    {
        [Required]
        [Display(Name = "Student Packet Id")]
        public Int64 StudentPacketId { get; set; }

        [Required]
        [Display(Name = "Student Id")]
        public Guid StudentId { get; set; }

        [Display(Name = "Amp ELA")]
        public AmpEla AmpEla { get; set; }

        public SelectList AmpElas { get; set; }

        public void Init()
        {
            AmpElas = AmpEla.Advanced.ToSelectListUsingDesc();
        }
    }
}

FPCS.Web.Admin/Models/StudentPacket2/AmpMathModel.cs
using System;
using System.Linq;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;

using FPCS.Core.Unity;
using FPCS.Core.Extensions;
using FPCS.Data;
using FPCS.Data.Repo;
using FPCS.Data.Enums;

namespace FPCS.Web.Admin.Models.StudentPacket2
{
    public class AmpMathModel
    {
        [Required]
        [Display(Name = "Student Packet Id")]
        public Int64 StudentPacketId { get; set; }

        [Required]
        [Display(Name = "Student Id")]
        public Guid StudentId { get; set; }

        [Display(Name = "Amp Math")]
        public AmpMath AmpMath { get; set; }

        public SelectList AmpMaths { get; set; }

        public void Init()
        {
            AmpMaths = AmpMath.Advanced.ToSelectListUsingDesc();
        }
    }
}

FPCS.Web.Admin/Models/StudentPacket2/CostModel.cs
using System;
using System.Linq;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;

using FPCS.Core.Unity;
using FPCS.Core.Extensions;
using FPCS.Data;
using FPCS.Data.Repo;
using FPCS.Data.Enums;

namespace FPCS.Web.Admin.Models.StudentPacket2
{
    public class CostModel
    {
        [Required]
        [Display(Name = "Student Packet Id")]
        public Int64 StudentPacketId { get; set; }

        [Required]
        [Display(Name = "Student Id")]
        public Guid StudentId { get; set; }

        [Display(Name = "Balance")]
        public Decimal Balance { get; set; }

        [Display(Name = "Total")]
        public Decimal Total { get; set; }

        [Display(Name = "Elective")]
        public Decimal Elective { get; set; }

        public Decimal ElectiveLimit { get; set; }

        public void Init()
        {
        }
    }
}

FPCS.Web.Admin/Models/StudentPacket2/FPCSCourseMiniModel.cs
using System;

using FPCS.Data.Enums;
using FPCS.Core.Extensions;

namespace FPCS.Web.Admin.Models.StudentPacket2
{
    public class FPCSCourseMiniModel
    {
        public Int64? FPCSCourseId { get; set; }

        public String Name { get; set; }

        public String Teacher { get; set; }

        public String Guardian { get; set; }

        public String Vendor { get; set; }

        public String Subject { get; set; }

        public String Cost { get; set; }

        public Semester Semester { get; set; }

        public String SemesterStr { get { return Semester.GetDescription(); } }
    }
}

FPCS.Web.Admin/Models/StudentPacket2/FPCSCoursesListOptions.cs
using System;

using FPCS.Core.jqGrid;

namespace FPCS.Web.Admin.Models.StudentPacket2
{
    public class FPCSCoursesListOptions
    {
        [GridProperty(ExtensionType.All, true)]
        public Int64? FPCSCourseId { get; set; }

        [GridProperty(ExtensionType.All, true, FilterOperation.Contains)]
        public String Name { get; set; }

        [GridProperty(ExtensionType.All, true, "Teacher.FullName", FilterOperation.Contains)]
        public String Teacher { get; set; }

        [GridProperty(ExtensionType.All, true, "Guardian.FullName", FilterOperation.Contains)]
        public String Guardian { get; set; }

        [GridProperty(ExtensionType.All, true)]
        public Int32? Subject { get; set; }

        [GridProperty(ExtensionType.Filter, false)]
        [GridProperty(ExtensionType.All, true)]
        public String Semester { get; set; }
    }
}

FPCS.Web.Admin/Models/StudentPacket2/ListPrintReimbursementModel.cs
using FPCS.Data.Enums;
using FPCS.Core.Extensions;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;

namespace FPCS.Web.Admin.Models.StudentPacket2
{
    public class ListPrintReimbursementModel
    {
        public ListPrintReimbursementModel()
        {
        }

        public List<PrintReimbursementModel> PrintReimbursements { get; set; }
    }
}

FPCS.Web.Admin/Controllers/StudentPacket2Controller.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Objects.SqlClient;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using FPCS.Core.Extensions;
using FPCS.Core.jqGrid;
using FPCS.Data;
using FPCS.Data.Enums;
using FPCS.Data.Repo;
using FPCS.Web.Admin.Code;
using FPCS.Web.Admin.Helpers.Access;
using FPCS.Web.Admin.Helpers.BudgetStudent;
using FPCS.Web.Admin.Helpers.BudgetStudent.Models;
using FPCS.Web.Admin.Helpers.FPCSCourses;
using FPCS.Web.Admin.Helpers.GoodAndService;
using FPCS.Web.Admin.Models.GoodAndService;
using FPCS.Web.Admin.Models.StudentPacket2;

namespace FPCS.Web.Admin.Controllers
{
	[FPCSAuthorize(Role.Admin, Role.Teacher, Role.Guardian)]
	public class StudentPacket2Controller : BaseController
	{
		public ActionResult Index(Guid id, Semester? semester)
		{
			try
			{
				var model = GetStudentPacket(id);
				model.Semester = semester;

				return View(model);
			}
			catch (Exception ex)
			{
				return Error(ex.Message);
			}
		}

		public ActionResult _Print(Guid id)
		{
			try
			{
				var model = new PrintStudentPacketModel();

				model.StudentPacketModel = GetStudentPacket(id);

				model.PrintAddress = (ConfigurationManager.AppSettings["PrintAddress"]);
				model.PrintState = (ConfigurationManager.AppSettings["PrintState"]);
				model.PrintPhone = (ConfigurationManager.AppSettings["PrintPhone"]);
				model.PrintFax = (ConfigurationManager.AppSettings["PrintFax"]);
				model.PrintDateNow = DateTime.Now.ToString("MM/dd/yyyy");

				model.Title = "Student Packet : " + model.StudentPacketModel.StudentName + " - Grade: " +
				              model.StudentPacketModel.StudentGradeStr;

				return PartialView(model);
			}
			catch (Exception ex)
			{
				return Error(ex.Message);
			}
		}

		public ActionResult _PrintReimbursement(Guid id)
		{
			try
			{
				var printAddress = (ConfigurationManager.AppSettings["PrintAddress"]);
				var printState = (ConfigurationManager.AppSettings["PrintState"]);
				var printPhone = (ConfigurationManager.AppSettings["PrintPhone"]);
				var printFax = (ConfigurationManager.AppSettings["PrintFax"]);
				var printDateNow = DateTime.Now.ToString("MM/dd/yyyy");

				var model = new ListPrintReimbursementModel();
				model.PrintReimbursements = new List<PrintReimbursementModel>();

				using (var uow = UnityManager.Resolve<IUnitOfWork>())
				{
					var guardians = uow.GetRepo<IFamilyRepo>().GetGuardiansByStudent(id).ToList();

                    var studentPacket = uow.GetRepo<IStudentPacketRepo>().Get(id, SchoolYear.SchoolYearId);

					var data = uow.GetRepo<IGoodServiceRepo>()
						.GetReimbursements(id, studentPacket.StudentPacketId)
						.Select(x => new
						{
							x.GoodServiceId,
							VendorName = x.Vendor.BusinessName,
							Item = x.Title,
							BudgetedAmount = x.UnitPrice*x.NumberOfUnits + x.ShippingHandlingFees,
							RequestedAmount = 0,
							Course = x.StudentPacketCourse.FPCSCourse.Name,
							StudentName =
								x.StudentPacketCourseId.HasValue ?
									x.StudentPacketCourse.StudentPacket.Student.LastName + ", " +
									x.StudentPacketCourse.StudentPacket.Student.FirstName + " ( " +
									(
										x.StudentPacketCourse.StudentPacket.Student.Grade == Grade.K ? "K" :
										x.StudentPacketCourse.StudentPacket.Student.Grade == Grade.G1 ? "G1" :
										x.StudentPacketCourse.StudentPacket.Student.Grade == Grade.G2 ? "G2" :
										x.StudentPacketCourse.StudentPacket.Student.Grade == Grade.G3 ? "G3" :
										x.StudentPacketCourse.StudentPacket.Student.Grade == Grade.G4 ? "G4" :
										x.StudentPacketCourse.StudentPacket.Student.Grade == Grade.G5 ? "G5" :
										x.StudentPacketCourse.StudentPacket.Student.Grade == Grade.G6 ? "G6" :
										x.StudentPacketCourse.StudentPacket.Student.Grade == Grade.G7 ? "G7" :
										x.StudentPacketCourse.StudentPacket.Student.Grade == Grade.G8 ? "G8" :
										x.StudentPacketCourse.StudentPacket.Student.Grade == Grade.G9 ? "G9" :
										x.StudentPacketCourse.StudentPacket.Student.Grade == Grade.G10 ? "G10" :
										x.StudentPacketCourse.StudentPacket.Student.Grade == Grade.G11 ? "G11" :
										x.StudentPacketCourse.StudentPacket.Student.Grade == Grade.G12 ? "G12" :
										x.StudentPacketCourse.StudentPacket.Student.Grade == Grade.G ? "G" : ""
									)
									+ " ) " :
								x.StudentPacketId.HasValue ?
									x.StudentPacket.Student.LastName + ", " +
									x.StudentPacket.Student.FirstName + " ( " +
									(
										x.StudentPacket.Student.Grade == Grade.K ? "K" :
										x.StudentPacket.Student.Grade == Grade.G1 ? "G1" :
										x.StudentPacket.Student.Grade == Grade.G2 ? "G2" :
										x.StudentPacket.Student.Grade == Grade.G3 ? "G3" :
										x.StudentPacket.Student.Grade == Grade.G4 ? "G4" :
										x.StudentPacket.Student.Grade == Grade.G5 ? "G5" :
										x.StudentPacket.Student.Grade == Grade.G6 ? "G6" :
										x.StudentPacket.Student.Grade == Grade.G7 ? "G7" :
										x.StudentPacket.Student.Grade == Grade.G8 ? "G8" :
										x.StudentPacket.Student.Grade == Grade.G9 ? "G9" :
										x.StudentPacket.Student.Grade == Grade.G10 ? "G10" :
										x.StudentPacket.Student.Grade == Grade.G11 ? "G11" :
										x.StudentPacket.Student.Grade == Grade.G12 ? "G12" :
										x.StudentPacket.Student.Grade == Grade.G ? "G" : ""
									)
									+ " ) " :
								"",
                            IsWithdrawal = x.StudentPacketCourseId.HasValue
                                            ? x.StudentPacketCourse.StudentPacket.Student.WithdrawalDate.HasValue ? true : false
                                            : x.StudentPacketId.HasValue ? x.StudentPacket.Student.WithdrawalDate.HasValue ? true : false : false,
							ObjCD =
								x.GoodOrService == GoodOrService.Good &&
								x.TypeRequisitionReimbursement == TypeRequisitionReimbursement.VendorService
									? "3030"
									: x.GoodOrService == GoodOrService.Service &&
									  x.TypeRequisitionReimbursement == TypeRequisitionReimbursement.TextbookCurriculum
										? "4020"
										: string.Empty
						})
						.OrderBy(x => x.StudentName)
						.ToList();

					var groupVendor = data.Select(x => x.VendorName).Distinct().OrderBy(x => x).ToList();

					foreach (var item in groupVendor)
					{
						var itemModel = new PrintReimbursementModel();

						itemModel.Reimbursements = data.Where(x => x.VendorName == item)
							.Select(x => new ReimbursementModel
							{
								GoodServiceId = x.GoodServiceId,
								Item = x.Item,
								BudgetedAmount = x.BudgetedAmount,
								RequestedAmount = x.RequestedAmount,
								Course = x.Course,
								StudentName = x.StudentName,
								ObjCD = x.ObjCD,
                                IsWithdrawal = x.IsWithdrawal
							})
							.ToList();

						itemModel.VendorName = item;
						itemModel.PrintAddress = printAddress;
						itemModel.PrintState = printState;
						itemModel.PrintPhone = printPhone;
						itemModel.PrintFax = printFax;
						itemModel.PrintDateNow = printDateNow;

						itemModel.Total = itemModel.Reimbursements.Sum(x => x.BudgetedAmount);

						if (guardians != null && guardians.Count >= 2)
						{
							itemModel.Title = string.Format(@"{0} : {1} & {2}", guardians.FirstOrDefault().LastName,
								guardians.FirstOrDefault().FirstName, guardians.LastOrDefault().FirstName);
						}
						else if (guardians != null && guardians.Count == 1)
						{
							itemModel.Title = string.Format(@"{0}, {1}", guardians.FirstOrDefault().LastName,
								guardians.FirstOrDefault().FirstName);
						}
						else
						{
							itemModel.Title = string.Empty;
						}

						model.PrintReimbursements.Add(itemModel);
					}
				}

				return PartialView(model);
			}
			catch (Exception ex)
			{
				return Error(ex.Message);
			}
		}

		public ActionResult _PrintReimbursementGeneralExpenses(Int64 id)
		{
			try
			{
				var printAddress = (ConfigurationManager.AppSettings["PrintAddress"]);
				var printState = (ConfigurationManager.AppSettings["PrintState"]);
				var printPhone = (ConfigurationManager.AppSettings["PrintPhone"]);
				var printFax = (ConfigurationManager.AppSettings["PrintFax"]);
				var printDateNow = DateTime.Now.ToString("MM/dd/yyyy");

				var model = new ListPrintReimbursementModel();
				model.PrintReimbursements = new List<PrintReimbursementModel>();

				using (var uow = UnityManager.Resolve<IUnitOfWork>())
				{
					var studentPacket = uow.GetRepo<IStudentPacketRepo>().Get(id);
					var guardians = uow.GetRepo<IFamilyRepo>().GetGuardiansByStudent(studentPacket.StudentId).ToList();

					var data = uow.GetRepo<IGoodServiceRepo>()
						.GetByGeneralExpenses(studentPacket.StudentPacketId)
						.Select(x => new
						{
							x.GoodServiceId,
							VendorName = x.Vendor.BusinessName,
							Item = x.Title,
							BudgetedAmount = x.UnitPrice * x.NumberOfUnits + x.ShippingHandlingFees,
							RequestedAmount = 0,
							Course = x.StudentPacketCourse.FPCSCourse.Name,
							StudentName =
								x.StudentPacketCourseId.HasValue ?
									x.StudentPacketCourse.StudentPacket.Student.LastName + ", " +
									x.StudentPacketCourse.StudentPacket.Student.FirstName + " ( " +
									(
										x.StudentPacketCourse.StudentPacket.Student.Grade == Grade.K ? "K" :
										x.StudentPacketCourse.StudentPacket.Student.Grade == Grade.G1 ? "G1" :
										x.StudentPacketCourse.StudentPacket.Student.Grade == Grade.G2 ? "G2" :
										x.StudentPacketCourse.StudentPacket.Student.Grade == Grade.G3 ? "G3" :
										x.StudentPacketCourse.StudentPacket.Student.Grade == Grade.G4 ? "G4" :
										x.StudentPacketCourse.StudentPacket.Student.Grade == Grade.G5 ? "G5" :
										x.StudentPacketCourse.StudentPacket.Student.Grade == Grade.G6 ? "G6" :
										x.StudentPacketCourse.StudentPacket.Student.Grade == Grade.G7 ? "G7" :

FPCS.Web.Admin/Views/StudentPacket2/_ASDTestingAgreement.cshtml
@model FPCS.Web.Admin.Models.StudentPacket2.AgreementModel

<div class="form-horizontal">
    <div class="row-fluid">
        <div class="span12">
            <div class="control-group">
                <div>
                    Family Partnership Charter School is required to test all enrolled students in grades 3-9 in mandatory state testing to comply with No Child Left Behind legislation.
                </div>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="control-group">
                <div>
                    FPCS has only reached Adequate Yearly Progress (AYP) in test participation and graduation rates twice in its 10 year history. The school is also required to participate in a universal screening for a reading assessment for students in Grades K-6. We need your help!
                </div>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="control-group">
                <div>
                    *All 11th Grade Students need take the WorkKeys testing to qualify for the Alaska Performance Scholarships.
                </div>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="control-group">
                <div>
                    *Please agree to this even if your student is in grades K-2 or in 12th Grade and will not need to test this year.
                </div>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="control-group">
                <div>
                    <h3 class="lighter block green">By clicking on a sign button, I Acknowledge that Statewide Testing is a requirement.  </h3>
                </div>
            </div>
        </div>
    </div>

    <table id="studentsInFamily" class="table table-bordered">
        <thead>
            <tr>
                <th>Student Name</th>
                <th></th>
                <th></th>
            </tr>
        </thead>

        <tbody>

            @foreach (var item in Model.Students)
            {
                <tr>
                    <td>
                        @Html.DisplayTextFor(x => item.StudentName)
                    </td>
                    <td>
                        @if (item.IsASDTASigned)
                        {
                            <span>
                                Signed: @item.ASDTAGuardianSigner
                            </span>
                        }
                        else
                        {
                            <span>
                                (guardian has not yet signed for this student) 
                            </span>
                        }
                    </td>
                    <td>
                        @if (item.StudentId == Model.StudentId && !item.IsASDTASigned)
                        {
                            <button class="asdTASignClick" onclick="fpcs.studentPacket2.clickASDTAAgreement('@item.StudentId')">Sign</button>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script type="text/javascript">
    fpcs.studentPacket.initASDTAAgreementPage();
</script>

FPCS.Web.Admin/Views/StudentPacket2/_AmpMathEdit.cshtml
@model FPCS.Web.Admin.Models.StudentPacket2.AmpMathModel

@using (Html.BeginForm("_AmpMathEdit", "StudentPacket2", FormMethod.Post, new { id = "ampMathEditForm", @class = "" }))
{
    @Html.AntiForgeryToken()

    <div class="controls">
        @Html.ValidationSummary(true)
    </div>
    
    @Html.HiddenFor(x => x.StudentId)
    @Html.HiddenFor(x => x.StudentPacketId)

    <div class="control-group">
        @Html.LabelFor(x => x.AmpMath, new { @class = "control-label" })
        <div class="controls">
            <div class="input-append">
                @Html.DropDownListFor(x => x.AmpMath, Model.AmpMaths, new { @class = "input-xlarge", id = "ampMathId" })
                <button id="ampMathSend" class="btn btn-small btn-success">Save</button>
                <button id="ampMathCancel" class="btn btn-small btn-primary">Cancel</button>
            </div>
            @Html.ValidationMessageFor(m => m.AmpMath)
        </div>
    </div>
}

FPCS.Web.Admin/Views/StudentPacket2/_Elective.cshtml
@model FPCS.Web.Admin.Models.StudentPacket2.CostModel
@using FPCS.Core.Extensions

<div class="control-group">
    @Html.LabelFor(x => x.Elective, new { @class = "control-label" })
    <div class="controls">
        <div class="input-group">
            <div class="input-append">
                @if (Model.ElectiveLimit < Model.Elective)
                {
                    <input type="text" value="@Model.Elective" class="input-xlarge wdth76 clrRed" readonly="true" />
                }
                else
                {
                    <input type="text" value="@Model.Elective" class="input-xlarge wdth76" readonly="true" />
                }
            </div>
        </div>
    </div>
</div>

FPCS.Web.Admin/Views/StudentPacket2/_SponsorSignature.cshtml
@model FPCS.Web.Admin.Models.StudentPacket2.SponsorSignatureModel
@using FPCS.Core.Extensions

@Html.HiddenFor(x => x.TeacherId, new { id = "sponsorId" })
<div class="control-group">
    @Html.LabelFor(x => x.Signature, new { @class = "control-label" })
    <div class="controls">
        <div class="input-group">
            <div class="input-append">
                @if (Model.Signature.HasValue) {
                    <input type="text" name="Name" value="@Model.Signature.Value.GetDescription()" class="input-xlarge" readonly="true"/>
                }
                else
                {
                    <input type="text" name="Name" value="" class="input-xlarge" readonly="true" />
                }
                <button id="sponsorSignatureEdit" packetId="@Model.StudentPacketId" class="btn btn-small btn-primary">Edit</button>
            </div>
        </div>
    </div>
</div>

FPCS.Web.Admin/Views/StudentPacket2/_SponsorSignatureEdit.cshtml
@model FPCS.Web.Admin.Models.StudentPacket2.SponsorSignatureModel

@using (Html.BeginForm("_SponsorSignatureEdit", "StudentPacket2", FormMethod.Post, new { id = "sponsorSignatureEditForm", @class = "" }))
{
    @Html.AntiForgeryToken()

    <div class="controls">
        @Html.ValidationSummary(true)
    </div>
    
    @Html.HiddenFor(x => x.StudentPacketId)
    @Html.HiddenFor(x => x.TeacherId)

    <div class="control-group">
        @Html.LabelFor(x => x.Signature, new { @class = "control-label" })
        <div class="controls">
            <div class="input-append">
                @Html.DropDownListFor(x => x.Signature, Model.Signs, new { @class = "input-xlarge", id = "signId" })
                <button id="sponsorSignatureSend" class="btn btn-small btn-success">Save</button>
                <button id="sponsorSignatureCancel" class="btn btn-small btn-primary">Cancel</button>
            </div>
            @Html.ValidationMessageFor(m => m.Signature)
        </div>
    </div>
}

FPCS.Web.Admin/Views/StudentPacket2/_SponsorTeacher.cshtml
@model FPCS.Web.Admin.Models.StudentPacket2.SponsorTeacherModel

@Html.HiddenFor(x => x.TeacherId, new { id = "sponsorId" })
<div class="control-group">
    @Html.LabelFor(x => x.Name, new { @class = "control-label" })
    <div class="controls">
        <div class="input-group">
            <div class="input-append">
                <input type="text" name="Name" value="@Model.Name" placeholder="Teacher not selected" class="input-xlarge" readonly="true" />
                <button id="sponsorTeacherEdit" packetId="@Model.StudentPacketId" class="btn btn-small btn-primary">Edit</button>
            </div>
        </div>
    </div>
</div>

FPCS.Web.Admin/Views/StudentPacket2/_SponsorTeacherEdit.cshtml
@model FPCS.Web.Admin.Models.StudentPacket2.SponsorTeacherModel

@using (Html.BeginForm("_SponsorTeacherEdit", "StudentPacket2", FormMethod.Post, new { id = "sponsorTeacherEditForm", @class = "" }))
{
    @Html.AntiForgeryToken()

    <div class="controls">
        @Html.ValidationSummary(true)
    </div>
    
    @Html.HiddenFor(x => x.StudentPacketId)
    @Html.HiddenFor(x => x.Name)

    <div class="control-group">
        @Html.LabelFor(x => x.Name, new { @class = "control-label" })
        <div class="controls">
            <div class="input-append">
                @Html.DropDownListFor(x => x.TeacherId, Model.Teachers, new { @class = "input-xlarge", id = "sponsorId" })
                <button id="sponsorTeacherSend" class="btn btn-small btn-success">Save</button>
                <button id="sponsorTeacherCancel" class="btn btn-small btn-primary">Cancel</button>
            </div>
            @Html.ValidationMessageFor(m => m.TeacherId)
        </div>
    </div>
}

FPCS.Web.Admin/Views/StudentPacket2/_Zangle.cshtml
@model FPCS.Web.Admin.Models.StudentPacket2.ZangleModel

@Html.HiddenFor(x => x.StudentId, new { id = "studentId" })
<div class="control-group">
    @Html.LabelFor(x => x.Name, new { @class = "control-label" })
    <div class="controls">
        <div class="input-group">
            <div class="input-append">
                <input type="text" name="Name" value="@Model.Name" class="input-xlarge" readonly="true" />
                <button id="zangleEdit" packetId="@Model.StudentPacketId" class="btn btn-small btn-primary">Edit</button>
            </div>
        </div>
    </div>
</div>